version: 0.2
phases:
  install:
    commands:
      - npm install -g apidoc
      - git clone https://github.com/wolfbeacon/wolfbeacon-core-api
      - git clone https://github.com/wolfbeacon/wolfbeacon-hackalist-api
  build:
    commands:
      - apidoc -i wolfbeacon-core-api/api/views/ -i wolfbeacon-hackalist-api/src/main/kotlin/wolfbeacon/hackalist/
  post_build:
    commands:
      - aws s3 sync doc/ "s3://${BUCKET_NAME}" --acl public-read
